name: My Spec Build and Deploy
run-name: ${{ github.actor }} is building and deploying My Spec 🚀
on:
  push:
    branches:
      - gh-actions
jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
       node-version: '16'
    - uses: pnpm/action-setup@v4
      with:
        version: 8
    - name: Install dependencies
      run: pnpm install
    - name: Build
      run: pnpm docs:build

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: Ting-YA-Yang/my-spec
        TARGET_BRANCH: gh-actions
        BUILD_SCRIPT: pnpm install && pnpm docs:build
        BUILD_DIR: docs/.vuepress/dist