name: My Spec Build and Deploy
run-name: ${{ github.actor }} is building and deploying My Spec 🚀
on:
  push:
    branches:
      - gh-actions
jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: lock node version
      uses: actions/setup-node@v4
      with:
          node-version: 18.20.0

    - name: deploy
      uses: JamesIves/github-pages-deploy-action@4.1.3
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: Ting-YA-Yang/my-spec
        TARGET_BRANCH: gh-actions
        BUILD_SCRIPT: npm i pnpm -g && pnpm install && pnpm docs:build
        BUILD_DIR: docs/.vuepress/dist