name: My Spec Build and Deploy
run-name: ${{ github.actor }} is building and deploying My Spec 🚀
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout  ️
      uses: actions/checkout@v4

    - name: lock npm version
      uses: actions/setup-node@v4
      with:
          node-version: 16.18.0

    - name: lock pnpm version
      uses: pnpm/action-setup@v2.2.4
      with:
          version: 8.12.1
    
    - name: pnpm install and build
      run: npm i pnpm -g && pnpm install && pnpm docs:build

    - name: deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        access_token: ${{ secrets.ACCESS_TOKEN }}
        branch: gh-pages
        folder: docs/.vuepress/dist