name: My Spec Deploy
run-name: ${{ github.actor }} is deploying My Spec 🚀
on:
  push:
    branches:
      - gh-actions
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
       node-version: '16'
    - uses: pnpm/action-setup@v4
      with:
        version: 8
    - name: Install dependencies
      run: pnpm install
    - name: Build
      run: pnpm docs:build