name: My Spec Build and Deploy
run-name: ${{ github.actor }} is building and deploying My Spec 🚀
on:
  push:
    branches:
      - gh-actions
jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: lock node version
      uses: actions/setup-node@v4
      with:
          node-version: '20'
    
    - name: pnpm install and build
      run: npm i pnpm -g && pnpm install && pnpm docs:build

    - name: deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        branch: gh-actions
        folder: docs/.vuepress/dist